version: 2.1
executors:
  default:
    docker:
      - image: kesar/eos-dev:207-170
commands:
  build_project:
    description: "Build project"
    steps:
      - run:
          command: |
            chmod +x build.sh
            make build-local
      - store_artifacts:
          path: ./build/contracts/demo/demo.abi
          destination: demo.abi
          when: on_success
      - store_artifacts:
          path: ./build/contracts/demo/demo.wasm
          destination: demo.wasm
          when: on_success
  test:
    description: "Run Tests"
    steps:
      - run:
          command: |
            mkdir -p ./test-results
            make test-local
          environment:
            BOOST_TEST_LOG_FORMAT: JUNIT
            BOOST_TEST_LOG_SINK: test-results/junit.xml
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results/junit.xml
          destination: junit.xml
jobs:
  build_and_test:
    executor: default
    steps:
      - checkout
      - build_project
      - test
workflows:
  pr:
    jobs:
      - build_and_test
